### Linear Algebra
#### Foundation of Linear Algebra.
> Matrix is the foundation of linear algebra. 
> Any Matrix is made out of vectors.
> Vector itself is made out of scalars.


#### Scalars and Scalar operations.

In [1]:
# Scalar operations
a, b = 10, 2
# Math Operations
c = a + b
print(c)

12


In [2]:
c = a - b
print(c)

8


In [3]:
c = a * b
print(c)

20


In [4]:
c = a / b
print(c)

5.0


In [10]:
try :
    c = a // b
except ZeroDivisionError as e:
    print("Cannot divide by 0, Exception : ", e)
print(c)

5


In [16]:
# Can these operations work on vector?
a = [1,2,3]
b = [2,3]
c = a+b # This is treated as list instead of array
print(c)

[1, 2, 3, 2, 3]


In [ ]:
# using numpy
import numpy as np
a_np = np.array(a) # array a = [1,2,3]
b_np = np.array(b) # array b = [2,3]
b_np = np.array([2,3,4]) # Overriding with new numpy array
c_result_np = a_np + b_np # Will not work due to the shape of the vectors are not same (Here a has shape 3 and b has shape 2)
print(c_result_np)

[3 5 7]


In [ ]:
print(f"Multiplication : {a_np * b_np}\nDivision : {a_np / b_np}")
print(np.shape(c)) # To display the shape

Multiplication : [ 2  6 12]
Division : [0.5        0.66666667 0.75      ]
(5,)


#### Matrix - Introduction
> Optimal : To work with square matrix (with equal number of rows and columns)

#### Types of matrix:
* Row Matrix
* Column Matrix
* Rectangular Matrix (m!=n rows and columns are not equal)
* Square Matrix (Equal number of rows and columns)
* Diagonal Matrix ( Only diagonal elements are non-zero)
* Triangular Matrix
* Identity Matrix
* Null Matrix

#### Matrix Operations
* Equivalent matrix
* Matrix Additions

In [31]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[5,6]])

if (a.all() == b.all()):
    print("yes")
else:
    print("no")

yes


In [ ]:
# Determinant of a matrix
# if the determinant is 0 then the matrix is not of use.

In [48]:
# Matrix operations advanced.
# Determinant
a = np.array([[1,2], [5,6]])
print(np.linalg.det(a)) #determininant of a

-3.999999999999999


In [7]:
# Rank of a matrix
b = np.array([[1,3], [3,4]])
print(np.linalg.matrix_rank(b)) # Rank of the Matrix

2


In [2]:
import numpy as np

In [4]:
c = np.array([[1,2],[3,3]])
print(f"Printing the matrix :\n{c}")
print((np.linalg.norm(c))) # Default Norm 
print(np.linalg.norm(c, ord=1)) # L1 norm
print(np.linalg.norm(c, ord=np.inf)) #Infinity norm (maximum absolute row norm)

Printing the matrix :
[[1 2]
 [3 3]]
4.795831523312719
5.0
6.0


In [5]:
a = np.array([[1,2], [3,4]])
print(inv_a:=np.linalg.inv(a)) #inverse of a

[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
# Transpose of a matrix
a.T

array([[1, 3],
       [2, 4]])

In [8]:
a,b

(array([[1, 2],
        [3, 4]]),
 array([[1, 3],
        [3, 4]]))

In [9]:
a.dot(b)

array([[ 7, 11],
       [15, 25]])

In [10]:
# Test the inverse
print(inv_a)
a.dot(inv_a)

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
#Step 1: Read the File
#Step 2: Set X
#Step 3: Set Y
#Step 4: Compute m = np.linalg.inv(x.t.dot(x).dot(x.t).dot(y))
#Step 5: Compute ycap = m*x
#Step 6: Compute r2_Score(y, ycap)

In [12]:
import pandas as pd
# Read the data
df = pd.read_csv("height_weight_data.csv")
df.head(10)

,ID,HT,WT,HT1
0,1,"5'2""",64,62
1,2,"4'4""",37,52
2,3,"5'0""",43,60
3,4,"5'0""",51,60
4,5,"5'4""",65,64
5,6,"5'0""",44,60
6,7,"5'4""",82,64
7,8,"5'11""",75,71
8,9,"5'8""",45,68
9,10,"5'1""",50,61


In [14]:
X = df[['HT1']]
y = df['WT']
m = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
print(m)

[0.97871471]


In [15]:
# Emperical modelling and predictive modelling.
# Build the LR class. Build the fit and __init__ method
class LR:
    def __init__(self):
        # Initialize the weights/ slope as None
        self.m = None

    def fit(self, x_train, y_train):
        # Ensure x_train is a 2D array(N rows, 1 column)
        # and y_train is in a 1D array
        X = np.array(x_train).reshape(-1,1)
        y = np.array(y_train)

        # Calculate the slope using the Normal Equation : (X^T * X) ^(-1) * X^T *y

        self.m = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    def predict(self, X_test):
        # Ensure the test data is also 2D for the math to align
        X_test = np.array(X_test).reshape(-1,1)

        if self.m is None:
            raise ValueError("Not fitted yet")
        
        # y = m* x
        return X_test @ self.m

In [16]:
# Dummy Data: Height vs Weight (Assuming a direct relationship through the origin)
heights = [150, 160, 170, 180]
weights = [55, 60, 64, 70]

# Instantiate and train the model
model = LR()
model.fit(heights, weights)

print(f"Calculated Slope (m): {model.m[0]}") 
# Output will be the optimized slope

# Predict the weight of someone who is 175 cm tall
predicted_weight = model.predict([175])
print(f"Predicted Weight for 175cm: {predicted_weight[0]}")

Calculated Slope (m): 0.3777879341864717
Predicted Weight for 175cm: 66.11288848263256
