# NumPy
NumPy (Numerical Python) is a fundamental library in Python for numerical computations. It’s a versatile tool primarily used for its advanced multi-dimensional array support.

In [2]:
import numpy as np # import numpy library as np (alias)
import time # import time module
import sys

In [9]:
# Comparison between numpy array and a regular python array

a = [1,2,3,4,5,6,7,8,9] * 10000
start = time.time()
for i in range(len(a)):
    a[i] = a[i]*2

print("The time taken for the list:", time.time() - start)

The time taken for the list: 0.016829490661621094


In [19]:
a = [1,2,3,4,5,6,7,8,9]
np_array = np.array(a)
print(np_array)
np_array*2
print(np_array)
print("The time taken for the list:", time.time() - start)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
The time taken for the list: 46.126105308532715


In [33]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [23]:
b = np.array([[9.0,8.1,2.2],[6.0,5.0,2.3]])
print(b)

[[9.  8.1 2.2]
 [6.  5.  2.3]]


In [24]:
# Get the dimension
a.ndim

1

In [27]:
# Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [34]:
#Get type
a.dtype

dtype('int16')

In [30]:
#Get size
a.itemsize

8

In [31]:
# Get total size
a.size * a.itemsize

24

In [32]:
a.nbytes

24

In [36]:
# Using Python Lists
python_list1 = [1, 2, 3, 4, 5]
python_list2 = [6, 7, 8, 9, 10]
result = [a + b for a, b in zip(python_list1, python_list2)]
print(result)

[7, 9, 11, 13, 15]


In [37]:
# Using NumPy Arrays
import numpy as np
np_array1 = np.array([1, 2, 3, 4, 5])
np_array2 = np.array([6, 7, 8, 9, 10])
result = np_array1 + np_array2
print(result)

[ 7  9 11 13 15]


In [40]:
arr_dim = np.array(0)
print(arr_dim.ndim) # Outputs 0 due to Scalar value

0


In [44]:
arr_dim = np.array([[[]]])
print(arr_dim.ndim)
print(arr_dim.shape)

3
(1, 1, 0)


In [ ]:
a = np.zeros(10, dtype="int16")
a = np.arange(1,10,2) # start, stop and step value
print(a)

[1 3 5 7 9]


In [55]:
# linspace
# it helps to create evenly spaced numbers
arr = np.linspace(0,1,9) # Start, Stop and no. of values between them
print(arr)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]


In [56]:
# Logarithmic scale array
arr = np.logspace(1,3,3) #logarithmic scale array -> 10^1 -> 10^3
arr

array([  10.,  100., 1000.])

In [58]:
arr = np.zeros(10) #creates an array full of zeros
print(arr)
arr_1 = np.ones([4,2], dtype="int16")
print(arr_1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [61]:
arr = np.full(10,2) # 10 values with all elements being 2
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4], 7.1) # It takes row, column and default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [65]:
arr = np.empty([2,3]) # Unintialized array -> Create an array 
arr

array([[9. , 8.1, 2.2],
       [6. , 5. , 2.3]])

In [67]:
arr_rand = np.random.rand(10) # Generates random float numbers
print(arr_rand)

[0.9737929  0.1699239  0.81446474 0.57729803 0.67392759 0.75608675
 0.95373335 0.85728816 0.75109924 0.81209829]


In [68]:
arr_rand = np.random.rand(2,3) # Generates random float numbers
print(arr_rand)

[[0.77030632 0.20669479 0.44812539]
 [0.84319125 0.78371097 0.11498449]]


In [74]:
arr_rand = np.random.randn(2,3) # Random numbers with normal distribution
print(arr_rand)

[[ 0.28909362  0.84599558 -0.40978843]
 [ 1.90429986 -1.20645753  1.19769499]]


In [85]:
arr = np.random.randint(0,100,size=(2,3)) # Random integers
print(arr)

[[73 43 33]
 [22 85 68]]


# NumPy Data types and Type casting

In [ ]:
arr = np.array([1,2,3.2,4,5,6,7], dtype="int8")
arr2=np.array([1,2,3])


array([1, 2, 3, 4, 5, 6, 7], dtype=int8)